### ISSUE TITLE
v10 Cluster3D points are not saved

### ISSUE THREAD

**Issue by bear-is-asleep** [SBNSoftware/sbndcode#638]
## I'm submitting a ...

- [x] bug report

Cluster3D points are not saved, so no truth pointwise analysis can be done.

## Checklist
- [x] I've added at least 1 label under `Labels`
- [x] Assigned a reviewer under `Assignees`

## Expected Behavior
`clust_label` in the `larcv` files should be occupied with labeled voxels.

## Current Behavior
`clust_label` is empty

## Possible Solution (optional)
~~I'm hoping this is just due to some labels being changed.~~ The product and module labels are identical in v9 and v10. Something fundamental happened in `Supera` (or upstream) which needs to be debugged.

## How to reproduce 

Produce a single event with any generator. I used particle gun
```bash

lar -c pgun.fcl -n 1
lar -c g4_sce.fcl -s prod*.root
lar -c detsim_sce.fcl -s prod*_G4*.root
lar -c reco1_mpvmpr.fcl -s prod*_G4*_DetSim*.root
```

On a machine with `spine` (you just need the repo for the driver)

```python

import sys
import yaml

SOFTWARE_DIR = '/sdf/data/neutrino/software/spine' # Change this path to your software install if you are not on S3DF
DATA_DIR = '/sdf/data/neutrino/bearc/larcv/v10_03_01_pgun_uniform/' #Or your path if local

# Set software directory
sys.path.insert(0, SOFTWARE_DIR)

#Spine imports
from spine.driver import Driver
from spine.utils.globals import *

cfg_path = 'mc.cfg'

#Data
DATA_PATH = DATA_DIR + 'larcv*.root'
cfg_data = yaml.safe_load(open(cfg_path, 'r').read().replace('DATA_PATH', DATA_PATH))

# prepare function configures necessary "handlers"
driver_data = Driver(cfg_data)

data = driver_data.process()

#Collect one image
entry = 0
clust_label = data['clust_label'][entry]

len(clust_label) #this is 0, but should be non-zero
```

```
#mc.cfg
io:
  loader:
    batch_size: 64
    shuffle: False
    num_workers: 4
    collate_fn: all
    dataset:
      name: LArCVDataset
      file_keys: DATA_PATH
      schema:
        input_data:
          parser: sparse3d
          #sparse_event: sparse3d_pcluster
          args:
            sparse_event_list:
              - sparse3d_reco
              - sparse3d_reco_chi2
              - sparse3d_reco_hit_charge0
              - sparse3d_reco_hit_charge1
              - sparse3d_reco_hit_charge2
              - sparse3d_reco_hit_key0
              - sparse3d_reco_hit_key1
              - sparse3d_reco_hit_key2
        seg_label:
          parser: sparse3d
          sparse_event: sparse3d_pcluster_semantics_ghost
        clust_label:
          parser: cluster3d
          cluster_event: cluster3d_pcluster
          particle_event: particle_corrected
          sparse_semantics_event: sparse3d_pcluster_semantics
          add_particle_info: true
          clean_data: true
        ppn_label:
          parser: particle_points
          particle_event: particle_corrected
          sparse_event: sparse3d_pcluster
        meta:
          parser: meta
          sparse_event: sparse3d_pcluster
        run_info:
          parser: run_info
          sparse_event: sparse3d_pcluster
        sed:
          parser: cluster3d
          args: {cluster_event: cluster3d_sed, add_particle_info: false, clean_data: false}
```
